Gum/Gui/Forms/ProjectPropertyGridWindow.cs
Gum/ToolCommands/GuiCommands.cs
Gum/Wireframe/CameraController.cs
Gum/Wireframe/EditingManager.cs
Gum/Wireframe/WireframeControl.cs
Gum/Wireframe/WireframeObjectManager.cs
InputLibrary/Cursor.cs

Now Gum immediately updates after:
* Object is moved or resized
* Zoom level is changed
* Mouse panning
Overall it makes things a lot smoother.

Triggering immediate updates

---

CommonFormsAndControls/CommonFormsAndControls.csproj
CsvLibrary/CsvLibrary.csproj
Gum/Gum.csproj
GumDataTypes/GumDataTypes.csproj
InputLibrary/InputLibrary.csproj
PerformanceMeasurementPlugin/PerformanceMeasurementPlugin.csproj
RenderingLibrary/RenderingLibrary.csproj
StateAnimationPlugin/StateAnimationPlugin.csproj
ToolsUtilities/ToolsUtilities.csproj
WpfDataUi/WpfDataUi.csproj
XnaAndWinforms/XnaAndWinforms.csproj

Fixed the Release configuration so that it can now be used to build binaries for release.

Fixed the Release configuration

---

Gum/Gui/Plugins/MainWindowPlugin.cs
Gum/Managers/ProjectManager.cs
Gum/Plugins/BaseClasses/PluginBase.cs
Gum/Plugins/PluginManager.cs

I realized I need one more event for the Perforce plugin to work correctly. It's named ElementSave to match the ProjectSave event.

Added (After)ElementSave plugin event

---

SkiaGum/DataTypes/DimensionUnitType.cs

Copy from Gum\GumDataTypes\DimensionUnitType.cs

---

Samples/GumFormsSample/KniGumFormsSample.BlazorGL/Pages/Index.razor
Samples/KniGumFromFile/KniGumFromFile.BlazorGL/Pages/Index.razor

related to 8cd0e96d30d5f549400c69ced146137f76a4b809

Fixed background color to solve alpha rendering issue.

---

MonoGameGum/MonoGameGum.csproj
RenderingLibrary/Graphics/Fonts/BitmapFont.cs
Samples/Tests/FntLoading/FntLoading.sln
Samples/Tests/FntLoading/FntLoading/Game1.cs

Improve font loading performance

---

WpfDataUi/Controls/ListBoxDisplay.xaml
WpfDataUi/Controls/ListBoxDisplay.xaml.cs

also added visibility changes to non-editing stackpanel when state is changed.

clear value instead of explicit white

---

Gum/Controls/MainPanelControl.xaml.cs

Fix the code by putting the correct objects with the correct variables

---

Gum/Wireframe/Ruler.cs

Add right-click functionality that will automatically remove the guide if clicked on

---

StateAnimationPlugin/MainStateAnimationPlugin.cs

Resolves #333 
I followed the pattern for Hotkeys and Project settings.
I don't know anything about animations so I don't know how to create them so I can validate things still work.
https://github.com/user-attachments/assets/e4df1734-5552-4806-9d72-8ad1165c2e74

Add middle-click remove tab.  Add Show/Hide wording change to MenuStrip.

---

Gum/Managers/StandardElementsManager.GumTool.cs
Gum/Managers/StandardElementsManager.cs
Gum/Plugins/InternalPlugins/VariableGrid/ElementSaveDisplayer.cs
SvgPlugin/Managers/DefaultStateManager.cs

This is just a PR so you can see the changes I've made so far, I'm missing a few I think because I can't get CUSTOM states that show up on a component to show up in the "States and Visibility" category.
Also, you may not like or want this feature this way.  I'm mainly just creating this for feedback and to see if I'm on the correct track.
This should eventually solve #330

Add most of the situations to eliminate the empty panel in variables

---

WpfDataUi/Controls/ComboBoxDisplay.xaml.cs
WpfDataUi/Controls/FileSelectionDisplay.xaml
WpfDataUi/Controls/FileSelectionDisplay.xaml.cs

Enhancement: Add right-click option to expose variables to labels

---

CommonFormsAndControls/TextInputWindow.cs
Gum/Commands/EditCommands.cs
Gum/Commands/GuiCommands.cs
Gum/Gui/Windows/DeleteOptionsWindow.xaml
Gum/Logic/RenameLogic.cs
Gum/Managers/MenuStripManager.cs
Gum/Plugins/ImportPlugin/Manager/ImportLogic.cs
Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.RightClick.cs
Gum/Plugins/InternalPlugins/VariableGrid/DeletingVariablesInCategoriesMessageBox.xaml
Gum/Services/EditVariableService.cs
Gum/Services/ExposeVariableService.cs
Gum/ToolCommands/ProjectCommands.cs
StateAnimationPlugin/MainStateAnimationPlugin.cs
StateAnimationPlugin/Views/MainWindow.xaml.cs
StateAnimationPlugin/Views/SubAnimationSelectionWindow.xaml

Relates to #413 
If you don't like the titles at all you can cancel the PR.  If you want the wording changed go ahead and change it or send me a message.
I tried to be consistent with case.  So if you did lowercase "state" I did lowercase "state", etc.
Found a message you didn't have the colon at the end ":" so I added it for consistency with the other popup windows.
This will resolve #437

437 add titles to all windows

---

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.RightClick.cs
ToolsUtilities/FileManager.cs

Update the logic so both use the same delete folder code.

---

Gum/Plugins/InternalPlugins/FileWatchPlugin/MainFileWatchPlugin.cs

Mark tab closeable so it picks up the middle click close functionality

---

Gum/Plugins/InternalPlugins/MenuStripPlugin/MenuStripManager.cs

Make it so that when you create a new project, it also prompts you to save it.

---

Gum/Managers/MenuStripManager.cs

Add documentation link to help

---

GumRuntime/GraphicalUiElement.cs

This actually didn't change any of the functionality, but reorganized the GraphicalUiElement methods so that it's easier to navigate and maintain.

396 how should gum handle circular dependencies between size and texture addresses

---

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs
WpfDataUi/Controls/AngleSelectorDisplay.xaml
WpfDataUi/Controls/FileSelectionDisplay.xaml

This fixes a few items, but more are needed for #468
items 5, 8, 11, and 13 are fixed or greatly enhanced from that issue.

Fix search checkbox width. Fix X button width.  Fix file selection buttons size scaling.

---

Gum/Plugins/ImportPlugin/Views/ImportFileView.xaml

Added label, clarification, and formatting of the xml

---

Gum/Plugins/InternalPlugins/VariableGrid/VariableRemoveButton.xaml

Relates to #468  this is item 22
Before Fix:
https://github.com/user-attachments/assets/230f2ed7-a463-49e6-8177-d373564aae7d
After fix
https://github.com/user-attachments/assets/6d6920a9-d5b5-4819-b206-57b3f6483544

Make it so the X isn't cut off

---

docs/_gum.linux.sh
docs/gum-tool/setup/README.md

I added a section called "Linux", and I made a modified setup_gum_mac.sh so handle Linux better, called [setup_gum_linux.sh](https://gist.githubusercontent.com/erievs/4c79b24930535248c3cc976692c91a65/raw/ad5947f09b3bddf8118b56757996e172f886a3aa/setup_gum_linux.sh) .

Updated the readme to include a Linux section to the guide.

---

docs/gum-tool/setup/README.md

The link pointed to the mac script.

Fixed setup_gum.linux.sh URL

---

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs

1. Dragging now scrolls treeview up and down if able to scroll. 
2. Node hovered over will highlight when dragging.
3. Also added in automatic node expanding on drag+hover.
Fixes #270
https://github.com/user-attachments/assets/18104321-c219-4ae4-82d1-82e7b3c9517d

Dragging now scrolls treeview up and down if able to scroll. 

---

XnaAndWinforms/GraphicsDeviceControl.cs

this replaces Present(...) to the backbuffer with a render target

GraphicsDeviceControl.DefaultRenderTarget

---

Samples/MVVM/MonoGameAndGum.csproj

Relative pathing was wrong for project references

Project references in Samples\MVVM\MonoGameAndGum fixed

---

XnaAndWinforms/GraphicsDeviceControl.cs

Before:
https://github.com/user-attachments/assets/73ebea3b-0c4e-48d3-aaf8-3eedc02bd8e9
After:
https://github.com/user-attachments/assets/080e64a6-421b-46dd-95f6-2104d3093ab3

This fixes the issue with the texture coordinates tab

---

.github/workflows/build-and-test.yaml

Adds automated testing of libraries to the build workflow.
This ensures core functionalities are automatically tested during each build, preventing regressions and maintaining code quality.

Add test projects to workflow

---

GumRuntime/GraphicalUiElement.cs
MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs
MonoGameGum.Tests/Runtimes/BindableGueTests.cs
MonoGameGum.Tests/Runtimes/LayoutTests.cs

Added auto tests for GetAnchor and GetDock
fixes #742

Added GetAnchor and GetDock

---

MonoGameGum.Tests/Forms/WindowTests.cs
MonoGameGum/Forms/Controls/FrameworkElementExt.cs
MonoGameGum/Forms/FormsUtilities.cs

Cursor no longer set by window when it is disabled.

Added FrameworkElement GetFrameworkElement

---

GumDataTypes/GumProjectSave.cs
GumRuntime/GraphicalUiElement.cs
MonoGameGum.Tests/Runtimes/GraphicalUiElementTests.cs

Add some api for play animation in MonoGame
PlayAnimation(int index);
PlayAnimation(string name);
PlayAnimation(AnimationRuntime animation);
UpdateAnimation(int index);
UpdateAnimation(string name);
UpdateAnimation(AnimationRuntime animation);
GetAnimation(int index);
GetAnimation(string name);
StopAnimation();
i did something wrong to make the source pr broken
source PR: #880

Add some api of animation runtime

---

MonoGameGum/Forms/Controls/FrameworkElement.cs
MonoGameGum/Forms/Controls/ListBoxItem.cs
MonoGameGum/Forms/Controls/MenuItem.cs
MonoGameGum/Forms/Controls/TextBoxBase.cs
MonoGameGum/Forms/DefaultVisuals/DefaultListBoxItemRuntime.cs
MonoGameGum/Forms/DefaultVisuals/DefaultMenuItemRuntime.cs
MonoGameGum/Forms/DefaultVisuals/DefaultTextBoxBaseRuntime.cs

Updated ListBoxItem and MenuItem to have Selected

[Breaking] Changed Selected->Focused state for TextBox and PasswordBox.

---

StateAnimationPlugin/ViewModels/ElementAnimationsViewModel.cs

Add Duplicate Animation drop down with functionality

---

.github/workflows/build-and-test.yaml
MonoGameGum/Clipboard/ClipboardImplementation.cs
MonoGameGum/MonoGameGum.csproj

Added multitargeting .NET8.0 on iOS

Removed TextCopy library from iOS,

---

FullClean.ps1
MonoGameGum/KniGum/KniGum.csproj
Samples/MonoGameGumFontLoading/MonoGameGumFontLoading/Content/obj/DesktopGL/net6.0/Content/.mgstats
Samples/MonoGameGumFromFile/MonoGameGumFromFile/Content/obj/DesktopGL/net6.0/Content/.mgstats
Samples/MonoGameGumImmediateMode/MonoGameGumImmediateMode/Content/obj/DesktopGL/net6.0/Content/.mgstats
Samples/MonoGameGumInCode/MonoGameGumInCode/Content/obj/DesktopGL/net6.0/Content/.mgstats

Prevent the ios stuff from leaking into the kni build

---

Gum/Commands/FileCommands.cs
Gum/Managers/FontManager.cs
Gum/Managers/ProjectManager.cs
Gum/Plugins/InternalPlugins/FileWatchPlugin/FileWatchControl.xaml
Gum/Plugins/InternalPlugins/FileWatchPlugin/FileWatchManager.cs
Gum/Plugins/InternalPlugins/FileWatchPlugin/FileWatchViewModel.cs
Gum/Plugins/InternalPlugins/FileWatchPlugin/MainFileWatchPlugin.cs
StateAnimationPlugin/Managers/AnimationCollectionViewModelManager.cs
ToolsUtilities/FilePath.cs

Added more diagnostics to file watch to include which files are being ignored.

Standardized wait time to 5 seconds

---

Gum/Managers/ObjectFinder.cs
Gum/Plugins/InternalPlugins/VariableGrid/MainVariableGridPlugin.cs
Gum/Plugins/InternalPlugins/VariableGrid/PropertyGridManager.cs
WpfDataUi/Controls/ComboBoxDisplay.xaml.cs

Removed updating variable grid during animation
Small perf improvement in ComboBox updating.

Cached element names on variable display

---

Gum/Commands/GuiCommands.cs
Gum/Plugins/InternalPlugins/MenuStripPlugin/MenuStripManager.cs
Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.RightClick.cs
Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs
Gum/ToolCommands/ProjectCommands.cs
ToolsUtilities/FilePath.cs

Fixed wrong slash direction when adding screens to subfolders.

Fixed to-lowering of folders when adding screens

---

GumCommon/GumCommon.csproj
GumDataTypes/GumDataTypesNet6.csproj
GumDataTypes/Variables/StateSave.cs
MonoGameGum/FnaGum/FnaGum.csproj
MonoGameGum/KniGum/KniGum.csproj
MonoGameGum/MonoGameGum.csproj
Runtimes/SkiaGum.Maui/SkiaGum.Maui.csproj
SkiaGum/SkiaGum.csproj
ToolsUtilities/ToolsUtilitiesStandard.csproj
raylib/RaylibGum/RaylibGum.csproj

Upped version numbers again for NuGet

State SetValue no longer requires a type

---

MonoGameGum/Forms/DefaultVisuals/TextBoxBaseVisual.cs

See the ticket for video showing before and after.
Fixes #1063

Make highlight flip the colors for the placeholder text so it doesn't disappear

---

Gum/Commands/GuiCommands.cs
Gum/Plugins/InternalPlugins/VariableGrid/AddVariableWindow.xaml
Gum/Plugins/InternalPlugins/VariableGrid/AddVariableWindow.xaml.cs
Gum/Plugins/InternalPlugins/VariableGrid/PropertyGridManager.cs
Gum/Plugins/InternalPlugins/VariableGrid/ViewModels/AddVariableViewModel.cs
Gum/Services/Builder.cs
Gum/Services/Dialogs/DialogService.cs
Gum/Services/Dialogs/DialogViewModel.cs
Gum/Services/Dialogs/DialogViewResolver.cs
Gum/Services/EditVariableService.cs

Moves the Add Variable window logic to use the DialogService for improved testability and consistency.
Removes the old window management code from GuiCommands and replaces it with a call to the DialogService.
asdf

Refactors Add Variable window to use DialogService

---

CodeOutputPlugin/Manager/CodeGenerator.cs
Gum/Plugins/InternalPlugins/Inheritance/MainInheritancePlugin.cs

Inheriting from NineSlice on a .Forms project now displays error in generated code.

Fixed inheritance changing default variables

---

Gum/Dialogs/AddInstanceDialogViewModel.cs
Gum/Dialogs/RenameElementDialogViewModel.cs
Gum/Managers/DragDropManager.cs
Gum/Managers/HotkeyManager.cs
Gum/Plugins/InternalPlugins/AlignmentButtons/CommonControlLogic.cs
Gum/Plugins/InternalPlugins/VariableGrid/SetVariableLogic.cs
Gum/Plugins/InternalPlugins/VariableGrid/StateReferencingInstanceMember.cs
Gum/Services/Builder.cs
TextureCoordinateSelectionPlugin/Logic/ControlLogic.cs
Tool/EditorTabPlugin_XNA/MainEditorTabPlugin.cs

This also reduces down to a single container

Remove SetVariableLogic.Self

---

MonoGameGum/Forms/DefaultVisuals/ButtonVisual.cs
MonoGameGum/Forms/DefaultVisuals/LabelVisual.cs

Found 2 white colors that needed to come from styling

---

Gum/CommandLine/CommandLineManager.cs
Gum/Commands/FileCommands.cs
Gum/Commands/GuiCommands.cs
Gum/MainWindow.cs
Gum/Plugins/InternalPlugins/MenuStripPlugin/MainMenuStripPlugin.cs
Gum/Plugins/InternalPlugins/MenuStripPlugin/MenuStripManager.cs
Gum/Program.cs
Gum/Services/Builder.cs
Gum/Services/Dialogs/DialogService.cs
Gum/Services/Dialogs/MainWindowHandleProvider.cs
Gum/Wireframe/WireframeObjectManager.RepresentationCreation.cs
Gum/Wireframe/WireframeObjectManager.cs

and overall just lessening the load in it's constructor.

Reduce dependencies on MainWindow

---

MonoGameGum.Tests/Runtimes/SpriteRuntimeTests.cs
MonoGameGum/GueDeriving/SpriteRuntime.cs

Fixed Spriteruntime SourceRectangle not working properly

---

CodeOutputPlugin/Manager/CodeGenerator.cs

1205/replace `Gum.DataTypes.DimensionUnitType` with just `DimensionUnitType`

---

Gum/Commands/GuiCommands.cs
Gum/Controls/MainPanelControl.xaml.cs
Gum/MainWindow.cs
Gum/Managers/ITabManager.cs
Gum/Program.cs
Gum/Services/Builder.cs

- Add ITabManager interface with tab management methods
- Implement ITabManager in MainPanelControl, and make implementations private
- Register ITabManager in DI container
- Update MainWindow to receive MainPanelControl as dependency
- Swap GuiCommands tab-related passthroughs to go through interface
- This prepares for extracting tab logic from GuiCommands

Create ITabManager interface and make MainPanelControl implement it

---

CodeOutputPlugin/Manager/CodeGenerator.cs
Gum/Managers/NameVerifier.cs

1221: Treat spaces as underscores

---

Gum/Plugins/PluginTab.cs

1227 - PluginTab.GotFocus

---

CodeOutputPlugin/Manager/CodeGenerator.cs
Tests/CodeGen_MonoGameForms_ByReference/CodeGenProject/Components/LabelContainer.Generated.cs
Tests/CodeGen_MonoGameForms_ByReference/CodeGenProject/Components/LabelContainer.cs
Tests/CodeGen_MonoGameForms_ByReference/CodeGenProject/Content/GumProject/CodeGenTestProject.gumx
Tests/CodeGen_MonoGameForms_ByReference/CodeGenProject/Content/GumProject/Components/LabelContainer.gucx
Tests/CodeGen_MonoGameForms_FullCodegen/Components/LabelContainer.Generated.cs
Tests/CodeGen_MonoGameForms_FullCodegen/Components/LabelContainer.cs
Tests/CodeGen_MonoGameForms_FullCodegen/Content/CodeGenProject.gumx
Tests/CodeGen_MonoGameForms_FullCodegen/Content/Components/LabelContainer.gucx

Fixed exposed Text variables on labels

---

docs/gum-tool/plugins/pluginbase.addandremovevariablesfortype.md

Removed misaligned indentation (docs update)

---

Gum/MainWindow.Designer.cs
Gum/MainWindow.cs
Gum/Program.cs
Gum/Services/Builder.cs
Gum/ViewModels/MainWindowViewModel.cs

and other various logic from MainWindow into it's viewmodel or app-entry

migrate static initializers to app-entry

---

RenderingLibrary/Camera.cs
RenderingLibrary/Graphics/SpriteRenderer.cs
Tool/EditorTabPlugin_XNA/ScrollbarService.cs
Tool/EditorTabPlugin_XNA/Services/CameraController.cs
Tool/EditorTabPlugin_XNA/Services/ScrollBarControlLogic.cs
Tool/EditorTabPlugin_XNA/Views/WireframeControl.cs

Default view is no longer centered

Gum tool now has a top-left aligned camera

---

Gum/Properties/AssemblyInfo.cs
GumRuntime/ElementSaveExtensions.GumRuntime.cs
GumRuntime/GraphicalUiElement.cs
MonoGameGum.Tests/Runtimes/AnimationRuntimeTests.cs
MonoGameGum/GueDeriving/NineSliceRuntime.cs
MonoGameGum/MonoGameGum.csproj
RenderingLibrary/Graphics/NineSlice.cs
ToolsUtilities/Network/NetworkManager.cs

PlayAnimation (index) is now an extension method

Added NineSliceRuntime.BorderScale

---

Gum/Managers/HotkeyManager.cs
Gum/Plugins/InternalPlugins/Hotkey/ViewModels/HotkeyViewModel.cs

fixes #1495
fixes #1255 - adding this here since I was in the area

1495 - fix undo/redo

---

CodeOutputPlugin/Manager/CodeGenerator.cs
GumCommon/GumCommon.csproj
GumCoreShared.projitems
GumRuntime/GraphicalUiElement.cs
MonoGameGum/FnaGum/FnaGum.csproj
MonoGameGum/GueDeriving/ContainerRuntime.cs
MonoGameGum/KniGum/KniGum.csproj
MonoGameGum/MonoGameGum.csproj
RenderingLibrary/Graphics/IRenderable.cs
RenderingLibrary/Graphics/InvisibleRenderable.cs
RenderingLibrary/Graphics/NineSlice.cs
RenderingLibrary/Graphics/Renderer.cs
RenderingLibrary/Graphics/SortableLayer.cs
RenderingLibrary/Graphics/Sprite.cs
RenderingLibrary/Graphics/SpriteBatchRenderableBase.cs
RenderingLibrary/Graphics/SpriteBatchStack.cs
RenderingLibrary/Graphics/SpriteRenderer.cs
RenderingLibrary/Graphics/Text.cs
RenderingLibrary/Math/Geometry/Line.cs
RenderingLibrary/Math/Geometry/LineCircle.cs
RenderingLibrary/Math/Geometry/LineGrid.cs
RenderingLibrary/Math/Geometry/LinePolygon.cs
RenderingLibrary/Math/Geometry/LineRectangle.cs
RenderingLibrary/Math/Geometry/SolidRectangle.cs
Runtimes/MonoGameGumShapes/Renderables/AposShapeBase.cs
Runtimes/MonoGameGumShapes/Renderables/Arc.cs
Runtimes/MonoGameGumShapes/Renderables/Circle.cs
Runtimes/MonoGameGumShapes/Renderables/RoundedRectangle.cs
SvgPlugin/SkiaInGumShared/Renderables/RenderableSkiaObject.cs

Fixed full file rendering support for screen sizes

Added batch rendering support
