GumDataTypes/GumProjectSave.cs
The previous behavior was that if the project file is not found, Gum would just go on trying to use the uninitialized gps variable and crash with NullReferenceException. Also, checking if file exists and then doing something is susceptible to race conditions. So I replaced all that with a try-catch block.
=> Fixed a bug where Gum would crash on start.

Gum/Managers/ProjectManager.cs, Gum/Plugins/BaseClasses/PluginBase.cs, Gum/Plugins/PluginManager.cs
1. A Perforce plugin needs to know when you're about to write to a file so it can check it out and remove the read-only flag. The existing plugin API did not have the necessary events so I added them.
2. I moved the
`PluginManager.Self.ProjectLoad(mGumProjectSave);`
to before
`ProjectManager.Self.SaveProject(forceSaveContainedElements:true);`
so plugins receive `ProjectLoad` before `ProjectSave` event, so that they can put their project specific initialization code in e.g. `HandleProjectLoad`.
3. I made the PluginManager class public so plugin can be aware of other plugins so that our Lua export plugin can ask the Perforce plugin to unlock destination files before export.
The Perforce plugin itself will come in a separate pull request if/when you accept this one.
=> Changed the plugin API to make a Perforce plugin possible

ToolsUtilities/FileManager.cs
Throw IOException instead of Exception so that plugins can catch the more specific exception. Also, changed the expression to include the caught exception in the InnerException of the newly thrown exception.
=> Changed FileManager.XmlDeserialize to throw a more correct exception

PerformanceMeasurementPlugin/ViewModels/PerformanceViewModel.cs
It's not critical, and WPF handles the exception, but it's annoying when debugging with Debug -> Exceptions... -> Thrown for NullReferenceException which normally means a bug in code. Returning zero seems like a reasonable choice.
=> Fixed a NullReferenceException in PerformanceMeasurementPlugin

Gum/Gui/Plugins/DeleteObjectPlugin.cs
I've made DeleteXmlComboBox and GetFileNameForObject public so other plugins can access this information. It is necessary for my Perforce plugin so it can remove the XML file from Perforce correctly.
=> Made some parts of DeleteObjectPlugin public

Gum/Managers/RenameManager.cs
Another thing required by the Perforce plugin. It lets plugins know when an ElementSave or other event is caused by a rename operation and not regular saving. I chose this solution because it's the least intrusive into the core Gum code and preserves compatibility with any existing third party plugins.
=> Made RenameManager.IsRenamingXmlFile available to plugins

Gum/Gum.csproj
Probably the most minor, least important thing, but at least now when I go to run Gum directly I'll see its proper icon instead of the Windows default icon for executables.
=> Set application icon

docs/README.md
I've updated the links on the [Gum intro page on flatredball.com](https://flatredball.com/documentation/tools/gum/gum-tutorials/tutorials-gum-introduction-and-setup/) and wanted to do the same here as well to avoid browser warnings on users' browsers.
=> Update to HTTPS URLs

WpfDataUi/Controls/SliderDisplay.xaml, WpfDataUi/DataUiGrid.xaml
These are the updates I thought were in the FRB PR. I didn't realize the controls were in a different repo
- Updated the XAML for the main editor to add a bit of spacing around the inside so objects aren't lined up against the window edge
- Property grid items have a little bit of padding at the bottom. This prevents the items from running too close together and adds visual spacing
=> Control style updates

Gum/Managers/NameVerifier.cs, Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.RightClick.cs
Context menu entries for adding child and parent to `Instances`.
Something missing is expanding the added node after the fact, I'm not sure how to retrieve the `TreeNode` from the `InstanceSave`, so the new node defaults to be closed.
=> Add child/parent Instance to instances (as opposed to only Elements)

GumRuntime/GraphicalUiElement.cs
If dimension units are `PercentageOfSourceFile` and a non-zero texture width/height was specified, then adjust the height to be based on the texture's width/height. This allows non-`ITextureCoordinate` ipsos to be used while correctly adjusting the dimensions as requested.
=> Set dimensions based on texture dimensions for any ipso

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs, Gum/Plugins/InternalPlugins/TreeView/ViewModels/SearchItemViewModel.cs
This PR got a ref to #144
The user can now search deeply inside the projet using a checkbox.
The PR also add a quality of life for the found elements with the path of the element.
Clicking on a found element directly focus it.
=> Text search and search item hierarchy

WpfDataUi/Controls/CheckBoxDisplay.xaml.cs, WpfDataUi/Controls/TextBoxDisplayLogic.cs, WpfDataUi/DataUiGrid.xaml
Replaces _some_ hard coded dataUI styling, to be more adaptive, additionally looks for resources set by glue to see if they can be used.
=> Open WpfDataUI up to glue theming

WpfDataUi/DataGridAttachedProperties.cs
Previous implementation assumes expander visual tree layout.
This implementation assumes naming in the controls template.
=> Refactor attached property implementation for Expander

WpfDataUi/Controls/AngleSelectorDisplay.xaml
- hardcoded width was unnecessary, and incompatible with different font sizes and font families
=> Remove hardcoded width for degree symbol

WpfDataUi/DataUiGrid.xaml
These minor adjustments go by nearly un-noticed in the variables tab but provides a cleaner layout for the theming/styling branch. It _may_ be worth looking at other areas outside of the variables tab in Glue, but these adjustments aren't more than 1-2 pixels so it really shouldn't negatively impact other areas.
=> Adjust padding and margins in DataUiGrid

Gum/Managers/ProjectManager.cs
This fixes the first part of #203, but I couldn't figure out how to get the menu to refresh for the list of Load Recent items.
I think Somehow the code needs to call MainRecentFilesPlugin.RefreshMenuItems();  also?
=> Recent project not showing just saved

RenderingLibrary/Graphics/Fonts/BitmapFont.cs
This fixes instances when a crash occurs because a font does not contain a space character.
Some fonts containing custom glyphs might not contain spaces.
=> Add font space null check

WpfDataUi/Controls/AngleSelectorDisplay.xaml, WpfDataUi/Controls/AngleSelectorDisplay.xaml.cs, WpfDataUi/Controls/CheckBoxDisplay.xaml, WpfDataUi/Controls/ComboBoxDisplay.xaml.cs, WpfDataUi/Controls/FileSelectionDisplay.xaml, WpfDataUi/Controls/FileSelectionDisplay.xaml.cs, WpfDataUi/Controls/NullableBoolDisplay.xaml, WpfDataUi/Controls/SliderDisplay.xaml, WpfDataUi/Controls/TextBoxDisplay.xaml, WpfDataUiCore/Controls/PlusMinusTextBox.xaml, WpfDataUiCore/Controls/PlusMinusTextBox.xaml.cs
fixes https://github.com/vchelaru/FlatRedBall/issues/1642
=> 1642 - hint-text wrapping

XnaAndWinforms/GraphicsDeviceControl.cs, XnaAndWinforms/RenderingError.cs
This should resolve #412
Unless there is a specific reason this isn't already being done, it works to fix the issue for me.
Steps to reproduce:
Open GUM
1. Lock your computer with WINDOWS+L
2. Unlock your computer
3. Graphics device is lost
4. Steps to fix:
Add this line of code at 216, and comment out the rest.
1. TryHandleDeviceReset(mRenderError);
2. If you still want a fallback, record if we've tried to reset or not, and then display the PaintUsingSystemDrawing instead.
I tested with above code change and it works fine for me.
=> Add fix for graphics device

Gum/Commands/GuiCommands.cs, Gum/Controls/MainPanelControl.xaml.cs, Gum/Gum.csproj, Gum/Plugins/BaseClasses/PluginBase.cs, Gum/Plugins/InternalPlugins/Hotkey/MainHotkeyPlugin.cs, Gum/Plugins/InternalPlugins/ProjectPropertiesWindowPlugin/MainPropertiesWindowPlugin.cs, Gum/Plugins/PluginTab.cs, Gum/Plugins/PluginTabItem.cs
This makes it so that the "View"->"Show Hotkeys" menu renames itself to "View"->"Hide Hotkeys" and visa-versa.
It also removes the Hotkeys panel when you click Hide Hotkeys.
Please provide review and feedback.
https://github.com/user-attachments/assets/d20f91cb-7de9-49ed-a09a-a3e8b051299f
Resolves #335
=> Add ability to hide the hotkeys menu, which also dynamically changes the VIEW menu item

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.RightClick.cs
Fixes #381 
You can decide if you like the work-around or not :)
https://stackoverflow.com/questions/1701457/directory-delete-doesnt-work-access-denied-error-but-under-windows-explorer-it
=> change directory to normal attributes before attempting a delete

GumDataTypes/GumProjectSave.cs
as explained I added an tiny shortcut function to reduce the repeating of  fetching a specific screen from a Project.
it work as the same as :
`var screen = mygumProject.Screen.find(item => item.Name = "name");`
=> Added  an shortcut function to fetch specific screen.

MonoGameGum/Forms/Controls/TextBoxBase.cs
This fixes #720
Method to test:
```csharp
private void MultilinTextBoxTutorial(StackPanel panelToAddTo)
{
var multiLinePanel = new StackPanel();
panelToAddTo.AddChild(multiLinePanel);
var label = new Label();
multiLinePanel.AddChild(label);
var leftToRight = new StackPanel();
leftToRight.Visual.ChildrenLayout = ChildrenLayout.LeftToRightStack;
leftToRight.Spacing = 3;
multiLinePanel.AddChild(leftToRight);
var startSelection = new Button();
startSelection.Text = "Start=5";
leftToRight.AddChild(startSelection);
var lengthSelection = new Button();
lengthSelection.Text = "Length=5";
leftToRight.AddChild(lengthSelection);
var multiLineTextBox = new TextBox();
multiLineTextBox.TextWrapping = TextWrapping.Wrap;
multiLineTextBox.Height = 140;
multiLinePanel.AddChild(multiLineTextBox); …
```
=> Add new SelectionChanged event

MonoGameGum/Forms/Controls/RadioButton.cs, MonoGameGum/Forms/Controls/ToggleButton.cs
Fixes #725
In the video I show that on startup, all the checkboxes I manually set are checked.
I show that manually changing them as a user they function correctly.
I show that when another element has code to set IsTrue it also correctly functions.
**NOTE:** The only "gotcha" with my fix is this..... If a user intentionally sets multiple IsChecked values on 2 or more Radio Buttons, and then AFTERWARDS adds them to the same parent, they will all show checked.  I feel this is acceptable, since someone would have to be intentionally trying to break things to set multiple to true themselves in code without a parent.  I could potentially work-around this by doing some logic in HandleParentChanged if you really are concerned with that scenario. …
=> 725 fix radiobutton istrue in initalize

docs/gum-tool/setup/README.md
My last pull request had some minor typos, so I needed to fix them.
I tweaked and reworded the auto Linux setup a bit.
I reworded the Linux prerequisites section a bit.
I added some more context to step 10 in the manual page, by explaining that BASH is what's most commonly used on Linux and macOS 10.14 and below, while ZSH is used on macOS 10.15 and higher. 
I changed it from /bin/Gum to /bin/gum, as it is more uniform across shells (on bash it'd be Gum, while fish it'd be gum).
=> Fixed Some Grammar, Typos, Reworded Some Stuff, and Tweaked The Manual Install Page

Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs
This is similar behavior now to how windows works in the explorer view.
Work towards issues with drag/drop, this fixes the issue where highlighted nodes loose their highlighting if you drag over them.
relates to #767
=> Preventing the highlighted nodes from changing color. 

MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs, MonoGameGum/Forms/Data/Binding.cs, MonoGameGum/Forms/Data/NpcBindingExpression.cs
fixes #776 
Implements StringFormat property on Binding to format the target value of a binding expression. This allows for formatting values displayed in UI elements without modifying the source data.
=> 776 - Add string format to bindings

setup_gum_mac.sh
The downloaded Gum zip file puts the Gum.exe in a /Debug folder.
This fixes failing to find the executable with the following error at the end when you ran the `Gum` command after running setup_gum_mac.sh.
```
wine: failed to open "/Users/patridge/.wine/drive_c/Program Files/Gum/Data/Gum.exe": c0000135
```
=> Mac setup: fix Gum zip missing path part

MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs, MonoGameGum/Forms/Data/NpcBindingExpression.cs
- null should be valid when updating a nullable value type property
- implements Binding.TargetNullValue, which was overlooked and unused.
- converts unnecessary async test methods to be void
=> fix: binding bug when validating null against nullable value types

MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs, MonoGameGum/Forms/Data/PropertyPathObserver.cs
Addresses an issue where replacing the BindingContext with a different type would not update the bound properties correctly.
Adds a test case to verify the correct behavior when replacing the BindingContext with an object of an unrelated type, ensuring that bindings are updated as expected.
Removes the initial OnValueChanged call in PropertyPathObserver to avoid potential issues with initial binding values.
=> fix: binding context replacement behavior.

MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs, MonoGameGum/Forms/Data/NpcBindingExpression.cs, MonoGameGum/Forms/Data/UntypedBindingExpressionBase.cs
Addresses a bug where binding to the BindingContext incorrectly triggered source updates, leading to potential invalid cast exceptions.
The BindingContext binding is now treated as a one-way binding, preventing unintended updates to the source. This ensures that the BindingContext is only used to update the target element, resolving the invalid cast issue.
=> fix: BindingContext update issue

MonoGameGum.Tests/Forms/FrameworkElementBindingTests.cs, MonoGameGum/Forms/Data/NpcBindingExpression.cs, MonoGameGum/Forms/Data/UntypedBindingExpressionBase.cs
fixes #820 
- Refines binding update behavior to avoid unnecessary source updates.
- Only updates the source when the target value has actually changed
- Includes small refactor to use properties instead of fields in NpcBindingExpression, and implemented caching of default values for value types.
=> 820 - FocusLostTrigger - Only update source when target has actually changed.

MonoGameGum/KniGum/KniGum.csproj, Samples/GumFormsSample/GumFormsSampleCommon/KniGumFormsSampleCommon.csproj, Samples/GumFormsSample/KniGumFormsSample.Android/KniGumFormsSample.Android.csproj, Samples/GumFormsSample/KniGumFormsSample.BlazorGL/KniGumFormsSample.BlazorGL.csproj, Samples/GumFormsSample/KniGumFormsSample.BlazorGL/wwwroot/Content/.gitignore, Samples/GumFormsSample/KniGumFormsSample.BlazorGL/wwwroot/index.html, Samples/GumFormsSample/KniGumFormsSample.DesktopGL/KniGumFormsSample.DesktopGL.csproj, Samples/GumFormsSample/KniGumFormsSample.WindowsDX/KniGumFormsSample.WindowsDX.csproj, Samples/GumFormsSample/MonoGameGumFormsSample/Content/KNIContent.mgcb, Samples/KniGumFromFile/KniGumFromFile.Android/KniGumFromFile.Android.csproj, Samples/KniGumFromFile/KniGumFromFile.BlazorGL/KniGumFromFile.BlazorGL.csproj, Samples/KniGumFromFile/KniGumFromFile.BlazorGL/wwwroot/index.html, Samples/KniGumFromFile/KniGumFromFile.DesktopGL/KniGumFromFile.DesktopGL.csproj, Samples/KniGumFromFile/KniGumFromFile.WindowsDX/KniGumFromFile.WindowsDX.csproj, Samples/KniGumFromFile/KniGumFromFileCommon/KniGumFromFileCommon.csproj, Samples/KniGumInCode/KniGumInCode.Android/KniGumInCode.Android.csproj, Samples/KniGumInCode/KniGumInCode.BlazorGL/KniGumInCode.BlazorGL.csproj, Samples/KniGumInCode/KniGumInCode.BlazorGL/wwwroot/index.html, Samples/KniGumInCode/KniGumInCode.DesktopGL/KniGumInCode.DesktopGL.csproj, Samples/KniGumInCode/KniGumInCode.WindowsDX/KniGumInCode.WindowsDX.csproj, Samples/KniGumInCode/KniGumInCodeCommon/KniGumInCodeCommon.csproj
Updates library and samples using KNI to version 4.1.9001, which includes:
- MonoGameGum\KniGum
- KniGumFormsSample
- KniGumFromFile
- KniGumInCode
Also added `MonoGameGumFormsSample/Content/KNIContent.mgcb` for the KniGumFormsSample.BlazorGL project. Previously it appeared to need the gum project files to be manually copied and included.
=> Update KNI version to 4.1.9001

.github/workflows/build-and-test.yaml
This PR extends the CI/CD pipeline to run build and test jobs on macOS and Linux in addition to Windows, improving cross-platform compatibility validation.
- **Updated `Build-and-Test` job**: Converted from single Windows runner to matrix strategy supporting:
- `windows-latest`
- `ubuntu-latest`
- `macos-latest`
- **Updated test reporting**: Updated test results naming to include OS identifier for better distinction between platform results
=> Add macOS and Linux support to Build and Test workflow

.github/workflows/build-and-test.yaml, .github/workflows/build-samples.yaml
Removes the `Build Samples`  job from the `build-and-test` workflow and moves it to a its own workflow that is a manual dispatch.
=> Move Build Samples to dispatch workflow

.github/workflows/build-and-test.yaml
Removed automatic build on push to master, only on PRs Added cache for SDK and NuGet to improve speeds.
=> Removed mac build since it's EXPENSIVE

Gum/Commands/FileCommands.cs, Gum/Managers/ProjectManager.cs, Gum/Plugins/InternalPlugins/FileWatchPlugin/FileWatchLogic.cs, Gum/Plugins/InternalPlugins/FileWatchPlugin/FileWatchManager.cs, StateAnimationPlugin/Managers/AnimationCollectionViewModelManager.cs, Tool/EditorTabPlugin_XNA/Views/Ruler.cs, Tool/EditorTabPlugin_XNA/Views/WireframeControl.cs
Applies the fix discussed here https://github.com/vchelaru/Gum/issues/873 to the rest of the usages of `FileWatchLogic.Self.IgnoreNextChangeOn`
Changes
FileWatchLogic.Self.IgnoreNextChangeOn TO FileWatchManager.Self.IgnoreNextChangeUntil with a one second timeframe 
The one second time frame was enough in my testing.
=> Fix linux refreshing issues

Gum/Plugins/InternalPlugins/StatePlugin/ViewModels/StateTreeViewModel.cs
remove unused empty constructor doing a service assignment and move the assignment to the constructor that is actually used.
=> fix state tree bug

CodeOutputPlugin/Manager/CodeGenerator.cs, Gum/DataTypes/StateSaveExtensionMethods.cs, Gum/Plugins/InternalPlugins/VariableGrid/StateReferencingInstanceMember.cs
Fixed right-click, make default on base type not resetting type properly
=> Setting Screen base type to empty screen no longer generates bad code

.github/workflows/sonarscanner.yml
This "SHOULD" make it so that it only does the SonarQube scan on PUSH.
I also added "sections" that should allow us to collapse them to see more.
=> Only scan on push to master.  Add groupings to collapse scan sections.

docs/gum-tool/setup/README.md, setup_gum_linux.sh
Added improvements to both the Linux manual and automated installation for Gum Tool.
Key items;
- Improved distro & distro version check functionality to be more flexable
- Added required installation packages for fresh WINE installs required by Gum Tool
- Improved automated installation for Gum Tool especially around the gum shell file
- Improved manual installation by aligning it to the automated install script (same wine prefix for example) and reduced steps required by doing multiline commands for smaller items (e.g. chmod +x)
Tested on a fresh Linux Mint 22.1 install for both automated and manual.
=> Improvements to Linux manual and automated Gum Tool Installation

Gum/Controls/MainPanelControl.xaml.cs, Gum/MainWindow.cs, Gum/Managers/HotkeyManager.cs, Gum/Plugins/InternalPlugins/Hotkey/MainHotkeyPlugin.cs, Gum/Plugins/InternalPlugins/Hotkey/Views/HotkeyView.xaml.cs, Gum/Plugins/InternalPlugins/StatePlugin/MainStatePlugin.cs, Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs, Gum/Plugins/InternalPlugins/VariableGrid/StateReferencingInstanceMember.cs, Gum/Services/Builder.cs, Tool/EditorTabPlugin_XNA/MainEditorTabPlugin.cs, Tool/EditorTabPlugin_XNA/SelectionManager.cs, Tool/EditorTabPlugin_XNA/Views/WireframeControl.cs
Changes the HotkeyManager from a singleton to a dependency-injected service.
This improves testability and reduces the reliance on global state.
Updates references to HotkeyManager to resolve through the service locator.
=> Remove HotkeyManager.Self

CodeOutputPlugin/MainCodeOutputPlugin.cs, Gum/Commands/GuiCommands.cs, Gum/Plugins/BaseClasses/PluginBase.cs, Gum/Plugins/InternalPlugins/AlignmentButtons/AlignmentMainPlugin.cs, Gum/Plugins/InternalPlugins/Behaviors/MainBehaviorsPlugin.cs, Gum/Plugins/InternalPlugins/Errors/MainErrorsPlugin.cs, Gum/Plugins/InternalPlugins/FileWatchPlugin/MainFileWatchPlugin.cs, Gum/Plugins/InternalPlugins/Hotkey/MainHotkeyPlugin.cs, Gum/Plugins/InternalPlugins/Output/MainOutputPlugin.cs, Gum/Plugins/InternalPlugins/ProjectPropertiesWindowPlugin/MainPropertiesWindowPlugin.cs, Gum/Plugins/InternalPlugins/StatePlugin/MainStatePlugin.cs, Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs, Gum/Plugins/InternalPlugins/Undos/MainPlugin.cs, Gum/Plugins/InternalPlugins/VariableGrid/PropertyGridManager.cs, Gum/Plugins/PluginTab.cs, PerformanceMeasurementPlugin/MainPlugin.cs, StateAnimationPlugin/MainStateAnimationPlugin.cs, TextureCoordinateSelectionPlugin/Logic/ControlLogic.cs, Tool/EditorTabPlugin_XNA/MainEditorTabPlugin.cs
- Add ITabManager dependency to PluginBase and inject it
- Update all plugins to use _tabManager instead of _guiCommands
- This separates tab management from other GUI operations
- Prepares for MVVM-based tab management implementation
- Remove all tab-related methods from GuiCommands class
- Tab management is now exclusively handled by ITabManager
- Clean separation of concerns between GUI commands and tab management
=> Update to use ITabManager instead of GuiCommands for tab operations

Gum/Commands/GuiCommands.cs, Gum/Controls/MainPanelControl.xaml.cs, Gum/Plugins/InternalPlugins/HideShowTools/MainHideShowToolsPlugin.cs, Gum/ViewModels/MainPanelViewModel.cs
Uses data binding for tool visibility
Removes direct calls to show/hide the tools panel.
Instead, introduces a dependency property bound to the view model. This allows plugins to toggle the tools panel's visibility through the view model, improving maintainability and decoupling.
=> Remove MainPanel references in GuiCommands related to tools visibility

Gum/DataTypes/ElementSaveExtensionMethods.cs, Gum/DataTypes/VariableSaveExtensionMethods.cs, Gum/Dialogs/AddCategoryDialogViewModel.cs, Gum/Managers/INameVerifier.cs, Gum/Managers/NameVerifier.cs, Gum/Plugins/InternalPlugins/VariableGrid/ColorPickerLogic.cs, Gum/Plugins/InternalPlugins/VariableGrid/ViewModels/AddVariableViewModel.cs, Gum/ToolCommands/ElementCommands.cs, Gum/ToolCommands/IElementCommands.cs, Gum/Undo/IUndoManager.cs, Gum/Undo/UndoManager.cs, GumDataTypes/IStateContainer.cs, GumDataTypes/Variables/VariableSave.cs, Tool/Tests/GumToolUnitTests/Managers/NameVerifierTests.cs, Tool/Tests/GumToolUnitTests/ViewModels/Dialogs/AddCategoryDialogViewModelTests.cs
Closes the first part of #1221 as finished (this time for real) — in PR #1232 I had forgot to handle also category names in name verification.
Before my changes, you could create a state category called `MyCategory` and another state category called `My Category` in the same element.
However, taking into account that we will replace spaces with underscores in Code Generation, that would cause name conflicts.
So now category name verification also treats spaces as underscores so we can safely implement that in CodeGen,
=> 1221 treat spaces as underscores in category name verification

Gum/Commands/GuiCommands.cs, Gum/Commands/IGuiCommands.cs, Gum/Controls/MainPanelControl.xaml, Gum/Managers/HotkeyManager.cs, Gum/Plugins/BaseClasses/PluginBase.cs, Gum/Plugins/InternalPlugins/MenuStripPlugin/MainMenuStripPlugin.cs, Gum/Plugins/InternalPlugins/MenuStripPlugin/MenuStripManager.cs, Gum/Plugins/InternalPlugins/ProjectPropertiesWindowPlugin/MainPropertiesWindowPlugin.cs, Gum/Plugins/PluginManager.cs, Gum/Services/Builder.cs, Gum/Services/IUiSettingsService.cs, Gum/Services/UiSettingsService.cs, Gum/ViewModels/MainPanelViewModel.cs, Tool/EditorTabPlugin_XNA/Editors/DimensionDisplay.cs, Tool/EditorTabPlugin_XNA/MainEditorTabPlugin.cs
This is mostly for the sake of rolling MainPanelControl off GuiCommands... There wasn't a lot of thought invested into this, so it may be temporary, but for now it seemed like an adequate approach that could be scaled for other settings.
=> Dedicated service for UI settings

Gum/Controls/MainPanelControl.xaml.cs, Gum/Plugins/InternalPlugins/ProjectPropertiesWindowPlugin/MainPropertiesWindowPlugin.cs, Gum/Plugins/PluginTab.cs
- fixes #1267
- also fixes a bug where tabs became user-closable that weren't prior to refactor. replacing the HideCommand with a plain Hide method for internal scenarios, and introduces a CloseCommand for scenarios where the user attempts to close the tab.
=> AutoSelect when viewing Properties tab

Gum/Commands/GuiCommands.cs, Gum/Commands/IGuiCommands.cs, Gum/Controls/CustomizableTextInputWindow.xaml.cs, Gum/Controls/ListBoxMessageBox.xaml.cs, Gum/Gui/Windows/DeleteOptionsWindow.xaml.cs, Gum/MainWindow.cs, Gum/Plugins/InternalPlugins/TreeView/ElementTreeViewManager.cs
- Remove last of MainPanelControl out of GuiCommands
- GuiCommands no longer needs to be initialized at all -- but specifically from MainWindow control
- Removes it as a MainWindow dependency
=> Remove MainWindow's dependency on GuiCommands

RenderingLibrary/Graphics/Sprite.cs
Integer division in C# truncates toward zero, so negative texture offsets produce wrong tile indices, breaking wrap on the left/top.
=> Fix texture looping with negative Texture Left

WpfDataUi/Controls/TextBoxDisplay.xaml.cs
This fixes a bug where text boxes wouldn't get updated if the app has lost focus while a TextBox has focus.
=> TextBox now suppresses focus if it has keyboard focus

GumFormsPlugin/MainGumFormsPlugin.cs, GumFormsPlugin/ViewModels/AddFormsViewModel.cs, GumFormsPlugin/Views/AddFormsWindow.xaml, GumFormsPlugin/Views/AddFormsWindow.xaml.cs
Uses the IDialogService to show the AddFormsWindow instead of directly instantiating and showing a Window.
This aligns with the standard approach for showing dialogs in Gum and enables more flexibility in how dialogs are presented.
The AddFormsWindow is now a UserControl rather than a Window to allow usage with the IDialogService.
=> Migrate AddFormsWindow
